### ISSUE TITLE
Temp files shouldn't go into nml_mods

### ISSUE THREAD

**Issue by XDelta** [astralchan/GifImporter#10]
Temporary files made while generating this should go into a /temp/ folder of some sort instead of directly in nml_mods

**Comment by kawaiiamber** [comment]
> Temporary files made while generating this should go into a /temp/ folder of some sort instead of directly in nml_mods

https://en.wikipedia.org/wiki/Temporary_folder

On the unis-based systems, I imagine `/tmp` would be a good place to store it. Though, IEEE 1003.1-2017 does specify a `TMPDIR` environmental variable (https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xbd_chap10.html). It seems that POSIX encourages using `TMPDIR` over `/tmp`. From what I can tell, the convention is to use `TMPDIR` if it exists, otherwise use `/tmp`: `${TMPDIR:-/tmp}`

On windows, if I understand correctly (could be wrong idk) the `TMP` or `TEMP` variables should be used to point to the temporary directory. That's pretty much all I'm aware of on the Windows side of things.

**Comment by astralchan** [comment]
Fixed in version 1.1.3

**Comment by astralchan** [comment]
I updated to use `System.IO.Path.GetTempPath()` in [4cfa8463316d6b3b7344feba16b8e922dd3df7b3](https://github.com/astralchan/GifImporter/commit/4cfa8463316d6b3b7344feba16b8e922dd3df7b3)
